spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
  #        reading inside config folder
  #        search-locations: "classpath:/config"
  #        reading from a file system location
          search-locations: "file:///Users//rojcarranza//Documents//config"
server:
  port: 8071