spring:
  application:
    name: "configserver"
  profiles:
    active: git
#    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/r0jjames/project-config.git
          default_label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
#        native:
  #        reading inside config folder
  #        search-locations: "classpath:/config"
  #        reading from a file system location
#          search-locations: "file:///Users//rojcarranza//Documents//config"
server:
  port: 8071