spring:
  application:
    name: "gatewayserver"
# To connect to config server
  config:
    import: "optional:configserver:http://localhost:8071/"
# Spring Cloud Gateway Configuration
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
#         /ACCOUNTS/api/create to /accounts/api/create
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
# Info for Eureka Server
info:
  app:
    name: "gatewayserver"
    description: "Personal Project Gateway Server Application"
    version: "1.0.0"

# Logging
logging:
  level:
    com:
      project:
        gatewayserver: DEBUG

# Circuit Breaker Configuration
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000