server:
  port: 9010
spring:
  application:
    name: "message"
  cloud:
    function:
      definition: email|sms # MessageFunctions.email MessageFunctions.sms
    stream:
      bindings:
        emailsms-in-0:
          destination: send-communication # Subscribed to send-communication Queue
          group: ${spring.application.name}
        emailsms-out-0:
          destination: communication-sent # Produce to communication-sent Queue
      kafka:
        binder:
          brokers:
            - localhost:9092
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    connection-timeout: 10s
