
spring:
  application:
    name: eurekaserver
  config:
#    eurekaserver.yml
    import: "optional:configserver:http://localhost:8071/"
# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  # To categorize the metrics
  metrics:
    tags:
      application: ${spring.application.name}