
spring:
  application:
    name: eurekaserver
  config:
    import: "optional:configserver:http://localhost:8071/"
# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  # To categorize the metrics
  metrics:
    tags:
      application: ${spring.application.name}
# Logging
logging:
  # Open Telemetry will follow this pattern
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"