build:
  version: "1.0"

accounts:
  message: "Welcome to Production Bank accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@rudzbank.com"
  onCallSupport:
    - (111) 555-1234
    - (111) 523-1345