build:
  version: "2.0"

accounts:
  message: "Welcome to QA accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@rudzbank.com"
  onCallSupport:
    - (222) 555-1234
    - (222) 523-1345